name: weeate

services:
  backend:
    image: cosmtrek/air
    working_dir: /app
    container_name: backend
    ports: 
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./backend/:/app/backend/:ro
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./.air.toml:/app/.air.toml
    restart: on-failure
  # backend:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   container_name: backend
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   restart: on-failure

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    env_file:
      - .env
    #ports:
    #  - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
    shm_size: 128mb

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: frontend
    env_file:
      - .env
      - .env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/app/frontend/src/
      - ./frontend/public/:/app/frontend/public/
      - ./.env:/app/.env
      - ./.env.dev:/app/.env.dev
    restart: on-failure

volumes:
  db_data:
